### ISSUE TITLE
Cannot find google-services.json

### ISSUE THREAD

**Issue by anshulkhemani** [SubhamTyagi/loco-answers#273]
When I am trying to compile the code you provided, it provides this error. Can you provide this file?

**Comment by marishlalwani** [comment]
You're supposed to enable it from Google Console I guess!

**Comment by anshulkhemani** [comment]
> You're supposed to enable it from Google Console I guess!

Can you please tell me how can I do it?

**Comment by marishlalwani** [comment]
Maybe it's Firebase issue. Or you can check app/director to see if the file exists! Not sure though!

**Comment by SubhamTyagi** [comment]
@anshulkhemani 

This file contains api keys, outh_client etc that are associated with my firebase account. These keys are to be kept in secret. i added this file to . gitignore file so that it can't be made public. 

Solution for you:
Either remove firebase from your repo 
Or get this file form firebase.

There is also  another api property file for fabric i.e  `fabric.properties`. if  stuck in error for fabric then do same for fabric
