### ISSUE TITLE
Bro I know we asking too much from you but I will be happy if you can tell me that how to set and use your app for best accuracy and results. 

### ISSUE THREAD

**Issue by royalchauhan** [SubhamTyagi/loco-answers#68]

**Comment by SubhamTyagi** [comment]
On main screen of app i given some optional instructions for better performance .
I suggest you to always switch on the accessibility service just before game. Because Android battery optimization killed background services. If you are happy in setting ignore optimization, auto start you can do these also //(these options are optional)

**Comment by royalchauhan** [comment]
Bro please do something about the last question because it is always wrong
on every trivia game. Otherwise leave it as it is because all 9 questions
are right. Thank you for reading and replying.
